steps:
  # Passo 1: Construir a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'southamerica-east1-docker.pkg.dev/avid-influence-474915-r5/cloud-run-source-deploy/posgo-desafios/weather-api:$COMMIT_SHA'
      - '.'

  # Passo 2: Fazer o push da imagem para o Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'southamerica-east1-docker.pkg.dev/avid-influence-474915-r5/cloud-run-source-deploy/posgo-desafios/weather-api:$COMMIT_SHA'

  # Passo 3: Fazer o deploy da imagem no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'weather-api'
      - '--image'
      - 'southamerica-east1-docker.pkg.dev/avid-influence-474915-r5/cloud-run-source-deploy/posgo-desafios/weather-api:$COMMIT_SHA'
      - '--region'
      - 'southamerica-east1'
      - '--allow-unauthenticated'

images:
  - 'southamerica-east1-docker.pkg.dev/avid-influence-474915-r5/cloud-run-source-deploy/posgo-desafios/weather-api:$COMMIT_SHA'

# CORREÇÃO DO ERRO DE LOGS AQUI:
options:
  logging: CLOUD_LOGGING_ONLY